;; bison mode/flex mode
;; (require 'font-lock)
;; (require 'cc-mode)
;; (require 'bison-mode)
;; (add-to-list 'auto-mode-alist '("\\.y$" . bison-mode))
;; (add-to-list 'auto-mode-alist '("\\.yy$" . bison-mode))
;; (autoload 'bison-mode "bison-mode" t)
;; (add-to-list 'auto-mode-alist '("\\.l$" . flex-mode))
;; (add-to-list 'auto-mode-alist '("\\.ll$" . flex-mode))
;; (autoload 'flex-mode "flex-mode" t)
;; (add-to-list 'ac-modes 'bison-mode)
;; (add-to-list 'ac-modes 'flex-mode)
